# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/

image:
  file: .gitpod.Dockerfile

tasks:
  - init: pipenv sync --dev 
    command: pipenv run mkdocs serve

ports:
- port: 8080
  onOpen: open-preview